apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "640Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"

# Open in integrated Terminal
# k apply -f deployment.yaml
# k delete -f deployment.yaml
