apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: farrukh90/symmetrical-fortnight
      image: farrukhsadykov/runner:latest


---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runnerdeploy
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: example-runnerdeploy
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - farrukh90/symmetrical-fortnight
